name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Cargo registry
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-registry
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-stable-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-registry-
    - name: Cache Cargo index
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-index
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-stable-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-index-
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
